Commit Github Cache

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -9,11 +9,13 @@ jobs:
     steps:
       - name: Get code
         uses: actions/checkout@v3
+      - name: Check for package.lock.json
+      run: ls -al package.lock.json || echo "package.lock.json not found"  
       - name: Cache dependencies
         uses: actions/cache@v4
         with:
           path: ~/.npm
-          key: deps-node-modules-${{hashFiles('**/package.lock.json')}}
+          key: deps-node-modules-${{ hashFiles('package.lock.json') }}
       - name: Install dependencies
         run: npm ci
       - name: Lint code
@@ -32,7 +34,7 @@ jobs:
         uses: actions/cache@v4
         with:
           path: ~/.npm
-          key: deps-node-modules-${{hashFiles('**/package.lock.json')}}
+          key: deps-node-modules-${{hashFiles('package.lock.json')}}
       - name: Install dependencies
         run: npm ci
       - name: Build website
